- name: install debian python packages
  apt:  name={{ item }} state=present update_cache=yes
  with_items:
    - python
    - python-pip
    - python-dev
    - virtualenv
    - apache2
    - libapache2-mod-wsgi
  when: ansible_distribution == 'Debian'

- name: install debian python packages
  apt:  name={{ item }} state=present update_cache=yes
  with_items:
    - python
    - python-pip
    - python-dev
    - python-virtualenv
    - apache2
    - libapache2-mod-wsgi
  when: ansible_distribution == 'Ubuntu'

- name: install prequisites
  apt: name={{item}} state=present
  with_items:
    - openssl
  when: flask_wsgi_ssl_cert is defined or flask_wsgi_ssl_cert_path is defined 

- name: enable mod_ssl
  shell: a2enmod ssl
  become: yes
  when: flask_wsgi_ssl_cert is defined or flask_wsgi_ssl_cert_path is defined 

- name: install debian extras
  apt:  name={{ item }} state=present
  with_items: "{{apt_packages|default([])}}"